blog/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("posts.urls")),
]

posts/urls.py
from django.urls import path
from . import views
app_name = "posts"
urlpatterns = [
    path("", views.posts_list, name="list"),
    path("<int:post_id>/", views.post_details, name="details"),
    path("new/", views.post_create, name="create"),

]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f'{self.author} - {self.title}'

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

posts/views.py
from .models import Post
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .forms import PostForm
# Create your views here.

def posts_list(request):
    # posts = Post.objects.filter(status="published")
    # page_number = request.GET.get("page", 1)
    # per_page = request.GET.get("per_page", 50)
    # paginator = Paginator(posts, per_page)

    # page_obj = paginator.page(page_number)

    return render(request, "posts/list.html")
# , {"page_obj": page_obj}


def post_details(request, post_id):
    form = None
    post = get_object_or_404(Post, id=post_id, status="published")

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()

    if request.user == post.author:
        form = PostForm(instance=post)

    # post = Post.objects.get(id=post_id, status="published")
    return render(request, "posts/details.html", {"post": post, "form": form})


def post_create(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            if request.user.is_superuser:
                post.status = "published"
            post.save()
            return redirect("posts:list")
    return render(request, "posts/create.html", {"form": form})

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:list' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:create' %}">Create Post</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/create.html
{% extends "posts/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

posts/templates/posts/details.html
{% extends "posts/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% if form %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% else %}
<h1>{{ post.title }}</h1>
<p><small>By {{ post.author }} on {{ post.posted_at|date }}</small></p> 
{% comment %} post.posted_at|date:"d.m.Y H:i" {% endcomment %}
<p>{{ post.content }}</p>
{% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
{% endif %}
{% endif%}
{% endblock %}

posts/templates/posts/list.html
{% extends "posts/base.html" %}

{% block content %}

<h1>Posts</h1>
<ul>
{% for post in page_obj %}
    <li><a href="{% url 'posts:details' post.id %}">{{ post.title }}</a></li>
{% endfor %}
</ul>

  {% if page_obj.has_other_pages %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}&per_page={{ page_obj.paginator.per_page }}">
                        Previous
                    </a>
                </li>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
                {% comment %}
                    This conditional allows us to display up to 3 pages before and after the current page
                    If you decide to remove this conditional, all the pages will be displayed

                    You can change the 3 to any number you want e.g
                    To display only 5 pagination items, change the 3 to 2 (2 before and 2 after the current page)
                {% endcomment %}
                {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                    {% if page_obj.number == page_number %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_number }}&per_page={{ page_obj.paginator.per_page }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}&per_page={{ page_obj.paginator.per_page }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}&per_page={{ page_obj.paginator.per_page }}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&per_page={{ page_obj.paginator.per_page }}">
                        Last
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{% endblock %}